// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu8uGbgnhQZJCzYJN3OLlUxZyO_dMzv0Y',
    appId: '1:68222759315:web:4763945941626aececf866',
    messagingSenderId: '68222759315',
    projectId: 'cw06-ea27f',
    authDomain: 'cw06-ea27f.firebaseapp.com',
    storageBucket: 'cw06-ea27f.firebasestorage.app',
    measurementId: 'G-EPHDZQB146',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe027Imowm-DcfN7Edb_eUJrkFxzTDDPU',
    appId: '1:68222759315:android:41d2035bdbbf7705ecf866',
    messagingSenderId: '68222759315',
    projectId: 'cw06-ea27f',
    storageBucket: 'cw06-ea27f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw6nbkBAcl7zYEFLSx_5UNTlGkG544r0w',
    appId: '1:68222759315:ios:17e7d1e8b480c301ecf866',
    messagingSenderId: '68222759315',
    projectId: 'cw06-ea27f',
    storageBucket: 'cw06-ea27f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw6nbkBAcl7zYEFLSx_5UNTlGkG544r0w',
    appId: '1:68222759315:ios:17e7d1e8b480c301ecf866',
    messagingSenderId: '68222759315',
    projectId: 'cw06-ea27f',
    storageBucket: 'cw06-ea27f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu8uGbgnhQZJCzYJN3OLlUxZyO_dMzv0Y',
    appId: '1:68222759315:web:bf0c41e943da1fcdecf866',
    messagingSenderId: '68222759315',
    projectId: 'cw06-ea27f',
    authDomain: 'cw06-ea27f.firebaseapp.com',
    storageBucket: 'cw06-ea27f.firebasestorage.app',
    measurementId: 'G-GF7EX848RB',
  );
}
